apiVersion: v1
kind: Service
metadata:
  name: fdc-sql-proxy-replica-svc
  namespace: fdc-apps
  annotations:
    networking.gke.io/load-balancer-type: "Internal"
spec:
  type: LoadBalancer
  loadBalancerIP: 10.3.1.11
  selector:
    app: fdc-sql-proxy-replica
  ports:
  - protocol: TCP
    port: 3306
    targetPort: 3306
